--------------------------------------------------------------------
--- Dependencies
--------------------------------------------------------------------
local _SERVICE = require(script.Parent._SERVICE)

--------------------------------------------------------------------
--- Types
--------------------------------------------------------------------
export type PlayerDeathHandler = _SERVICE.SERVICE<PlayerDeathHandler> & {}

return (nil :: any) :: PlayerDeathHandler
