[package]
name = "cosinewaves/loader"
description = "A lightweight, lifecycle-aware module loader for Roblox."
version = "1.2.4"

license = "MIT"
authors = ["cosinewaves"]

realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["**"]
include = ["default.project.json", "lib", "lib/**", "LICENSE.txt", "wally.toml"]
private = false
