--------------------------------------------------------------------
--- Dependencies
--------------------------------------------------------------------
local _CONTROLLER = require("@game/StarterPlayer/StarterPlayerScripts/Client/Types/_CONTROLLER")

--------------------------------------------------------------------
--- Types
--------------------------------------------------------------------
export type CmdrClient = _CONTROLLER.CONTROLLER<CmdrClient> & {}

return (nil :: any) :: CmdrClient
