--------------------------------------------------------------------
--- Dependencies
--------------------------------------------------------------------
local _CONTROLLER = require("@clientTypes/_CONTROLLER")

--------------------------------------------------------------------
--- Types
--------------------------------------------------------------------
export type CmdrClient = _CONTROLLER.CONTROLLER<CmdrClient> & {}

return (nil :: any) :: CmdrClient
