--------------------------------------------------------------------
--- Dependencies
--------------------------------------------------------------------
local _CONTROLLER = require(script.Parent._CONTROLLER)

--------------------------------------------------------------------
--- Types
--------------------------------------------------------------------
export type CmdrClient = _CONTROLLER.CONTROLLER<CmdrClient> & {}

return (nil :: any) :: CmdrClient
