--------------------------------------------------------------------
--- Dependencies
--------------------------------------------------------------------
local _SERVICE = require("@game/ServerScriptService/Server/Types/_SERVICE")

--------------------------------------------------------------------
--- Types
--------------------------------------------------------------------
export type CmdrServer = _SERVICE.SERVICE<CmdrServer> & {}

return (nil :: any) :: CmdrServer
