--------------------------------------------------------------------
--- Dependencies
--------------------------------------------------------------------
local _SERVICE = require("@game/ServerScriptService/Server/Types/_SERVICE")

--------------------------------------------------------------------
--- Types
--------------------------------------------------------------------
export type PlayerDeathHandler = _SERVICE.SERVICE<PlayerDeathHandler> & {}

return (nil :: any) :: PlayerDeathHandler
